server:
  port: 9002

spring:
    application:
        name: wbkdng-customers
    datasource:
        url: jdbc:postgresql://localhost:5432/wbkdng
        username: postgres
        password: Shadow230511
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                default_schema: backoffice


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka